name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_TOKYO }}
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.TOKYO_IP}}
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/easyun-web"
